---
- name: Installing and starting nginx server
  hosts: all
  become: true

  tasks: 
    - name: Installing nginx
      apt:
        name: nginx
        state: present
    - name: starting server
      service:
        name: nginx
        state: started
